version: 2.1

jobs:
  build:
    docker:
        - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make install
    #       name: run tests
    #       command: |
    #         . venv/bin/activate
    #         make test
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
      
workflows:
  test_my_app:
    jobs:
      - build